################ Chinese language ##################
[zh-cn]
languageName = "简体中文"
languageCode = "zh-CN"
contentDir = "content/chinese"
weight = 1
################ English language ##################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
