############# chinese navigation ##############

# main menu
[[main]]
name = "首页"
url = "/"
weight = 1

[[main]]
name = "资讯"
url = "/blog"
weight = 2

[[main]]
name = "关于"
url = "/about"
weight = 3

# footer menu
[[footer]]
name = "关于"
url = "/about"
weight = 1

[[footer]]
name = "隐私政策"
url = "/privacy-policy"
weight = 2

[[footer]]
name = "联系"
url = "/contact"
weight = 3